# -*- coding: utf-8 -*-
from . import res_company
from . import bim_project
from . import bim_department
from . import bim_documentation
from . import bim_purchase_requisition
from . import bim_mobile_warehouse
from . import purchase
from . import bim_maintenance
from . import stock
from . import uom
from . import product_template
from . import account_move
from . import bim_paidstate
from . import bim_config
from . import bim_task
from . import bim_budget
from . import bim_concepts
from . import bim_assets
from . import bim_miscellaneous
from . import res_users
from . import bim_checklist
from . import ticket_bim_category
from . import ticket_bim
from . import bim_object
from . import bim_part
from . import hr_employee
from . import bim_ite
from . import res_partner
from . import work_order
from . import bim_list_price_agreed
from . import ir_config_parameter
